version = 3.10.0

runner.dialect = scala3
runner.dialectOverride.allowSignificantIndentation = false
runner.dialectOverride.allowQuietSyntax = true

maxColumn = 100
indent.main = 2
indent.callSite = 2
indent.extendSite = 2

newlines.source = keep
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = false

rewrite.rules = [Imports]
rewrite.imports.sort = scalastyle
