application: bionicspirit-com
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: website/build/index.html
  upload: website/build/index.html
  expiration: "1d"
  http_headers:
    X-Url-Handler: mainpage

- url: /rss/?
  script: engine.main.app

- url: /docs/dialer.html
  script: engine.main.app

- url: /(.+/)
  static_files: website/build/\1index.html
  upload: website/build/(.+/)index.html
  expiration: "1d"
  http_headers:
    X-Url-Handler: index.html

- url: /(.+[.]html?)
  static_files: website/build/\1
  upload: website/build/(.+[.]html?)
  expiration: "1d"
  http_headers:
    X-Url-Handler: articles

- url: /(.*)
  static_files: website/build/\1
  upload: website/build/(.*)
  expiration: "365d"
  http_headers:
    X-Url-Handler: static-files

libraries:
- name: django
  version: "1.4"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^/?website/source/.*$
- ^/?website/Gemfile*$
- ^/?website/Rakefile*$
