application: bionicspirit-com
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: website/build/index.html
  upload: website/build/index.html
  expiration: "1d"
  http_headers:
    X-Url-Handler: mainpage

- url: /(.+/)
  static_files: website/build/\1index.html
  upload: website/build/(.+/)index.html
  expiration: "1d"
  http_headers:
    X-Url-Handler: index.html

- url: /(.+[.]html?)
  static_files: website/build/\1
  upload: website/build/(.+[.]html?)
  expiration: "1d"
  http_headers:
    X-Url-Handler: articles

- url: /(.*)
  static_files: website/build/\1
  upload: website/build/(.*)
  expiration: "365d"
  http_headers:
    X-Url-Handler: static-files

libraries:
- name: webapp2
  version: "2.5.2"
