:website:
  :id: "http://bionicspirit.com"
  :title: "Bionic Spirit"
  :description: "Building Stuff, Having Fun, Craving Profit"
  :hostname: "www.bionicspirit.com"
  :domain: "bionicspirit.com"
  :root_url: "https://www.bionicspirit.com"