#!/usr/bin/env ruby

require 'optparse'
require "json"

options = {}
parser = OptionParser.new do |opt|
  opt.on('--title TITLE') { |o| options[:title] = o }
end

parser.parse!
begin
  raise OptionParser::MissingArgument.new("--title") if options[:title].nil?

  now = Time.new
  slug_title = options[:title].strip.downcase.gsub(/^\W+|\W+$/, "").gsub(/\W+/, "-")
  slug = now.strftime("%Y-%m-%d") + "-" + slug_title + ".md"
  text = %{
---
title: #{options[:title].to_json}
tags:
  - Snippet
---
  }.strip

  dir_path = File.expand_path(File.join(File.dirname(File.expand_path(__FILE__)), "..", "_posts"))
  path = File.join(dir_path, slug)
  File.open(path, 'w') { |file| file.write(text) }
  exec("code \"#{dir_path}\" \"#{path}\"")
rescue
  puts parser.help
  raise
end
