#!/usr/bin/env ruby

require 'optparse'
require "json"

options = {:draft => false}
parser = OptionParser.new do |opt|
  opt.on('--title TITLE') { |o| options[:title] = o }
  opt.on('--draft') { |o| options[:draft] = true }
end

parser.parse!
begin
  raise OptionParser::MissingArgument.new("--title") if options[:title].nil?

  now = Time.new
  slug_title = options[:title].strip.downcase.gsub(/^\W+|\W+$/, "").gsub(/\W+/, "-")
  text = %{
---
title: #{options[:title].to_json}
image:
# image_caption:
# date:
# last_modified_at:
# generate_toc: true
tags: []
description: >
  Description here...
---

<p class="intro">
  Intro here...
</p>
  }.strip

  rel_dir_path =
    if options[:draft]
      "_drafts"
    else
      "_posts"
    end


  fname = slug_title + ".md"
  unless options[:draft]
    fname = now.strftime("%Y-%m-%d") + "-" + fname
  end

  project_path = File.expand_path(File.join(File.dirname(File.expand_path(__FILE__)), ".."))
  dir_path = File.join(project_path, rel_dir_path)
  path = File.join(dir_path, fname)
  puts "Created: #{rel_dir_path}/#{fname}"
  File.open(path, 'w') { |file| file.write(text) }
  exec("code \"#{project_path}\" \"#{path}\"")
rescue
  puts parser.help
  raise
end
