#!/usr/bin/env ruby

require 'optparse'
require "json"

options = {}
parser = OptionParser.new do |opt|
  opt.on('--title TITLE') { |o| options[:title] = o }
  opt.on('--author AUTHOR') { |o| options[:author] = o }
  opt.on('--link LINK') { |o| options[:link] = o }
end

parser.parse!
begin
  raise OptionParser::MissingArgument.new("--title") if options[:title].nil?
  raise OptionParser::MissingArgument.new("--link") if options[:link].nil?

  now = Time.new
  slug_title = options[:title].strip.downcase.gsub(/^\W+|\W+$/, "").gsub(/\W+/, "-")
  slug = now.strftime("%Y-%m-%d") + "-" + slug_title + ".md"
  text = %{
---
link: #{options[:link].to_json}
title: #{options[:title].to_json}
author: #{if options[:author] then options[:author].to_json else 'null' end}
date: #{now.strftime("%Y-%m-%d %H:%M:%S%z")}
tags: []
---
  }.strip

  dir_path = File.expand_path(File.join(File.dirname(File.expand_path(__FILE__)), "..", "_links"))
  path = File.join(dir_path, slug)
  File.open(path, 'w') { |file| file.write(text) }
  exec("code #{path}")
rescue
  puts parser.help
  raise
end
