#!/usr/bin/env ruby

require 'optparse'
require "json"

options = {}
parser = OptionParser.new do |opt|
  opt.on('--title TITLE') { |o| options[:title] = o }
end

parser.parse!
begin
  raise OptionParser::MissingArgument.new("--title") if options[:title].nil?

  now = Time.new
  slug_title = options[:title].strip.downcase.gsub(/^\W+|\W+$/, "").gsub(/\W+/, "-")
  slug = slug_title + ".md"
  text = %{
---
date: #{now.strftime("%Y-%m-%d %H:%M:%S %:z")}
last_modified_at: #{now.strftime("%Y-%m-%d %H:%M:%S %:z")}
---

# #{options[:title]}
}.strip
  dir_path = File.expand_path(File.join(File.dirname(File.expand_path(__FILE__)), ".."))
  path = File.join(dir_path, "_wiki", slug)
  File.open(path, 'w') { |file| file.write(text) }
  exec("code \"#{dir_path}\" \"#{path}\"")
rescue
  puts parser.help
  raise
end
