#!/usr/bin/env ruby

require 'tmpdir'

def exec(cmd)
  abort("Error encountered, aborting") unless system(cmd)
end

puts "CI=#{ENV['CI']}"
puts "CI_DEPLOY=#{ENV['CI_DEPLOY']}"

unless ENV['CI'] == 'true'
  abort("ERROR: Not running on top of CI, aborting!")
end

# Forcing a change to the root directory, if not there already
Dir.chdir(File.absolute_path(File.join(File.dirname(__FILE__), "..")))

if ENV['CI_DEPLOY'] == "true"
  exec("bundle exec jekyll build")
else
  exec("bundle exec jekyll build")
end

unless ENV['CI_DEPLOY'] == "true"
  puts "Skipping deployment, exiting!"
  exit 0
end

repository = "github.com/alexandru/alexn.org.git"
ghToken = ENV['GH_TOKEN']

unless ghToken
  puts "Missing GH_TOKEN environment value!"
  exit 1
end

destDir = Dir.mktmpdir
begin
  exec("rm -rf \"#{destDir}\"")
  exec("git clone \"https://#{ghToken}@#{repository}\" \"#{destDir}\" -b gh-pages")
  exec("rsync --filter='P .*' --delete-excluded -Pacv _site/ \"#{destDir}/\"")

  Dir.chdir(destDir) do |path|
    exec("git add .")
    exec('git config user.name "Alexandru Nedelcu"')
    exec('git config user.email "noreply@alexn.org"')
    exec('git commit -m "docs: update gh-pages"')
    exec("git push --force --quiet \"https://alexandru:#{ghToken}@#{repository}\" gh-pages:gh-pages")
  end
ensure
  exec("rm -rf \"#{destDir}\"")
end
